//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace LibEngine {

public class Engine : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal Engine(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Engine obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Engine() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          LibEnginePINVOKE.delete_Engine(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Engine(EngineOptions options) : this(LibEnginePINVOKE.new_Engine(EngineOptions.getCPtr(options)), true) {
    if (LibEnginePINVOKE.SWIGPendingException.Pending) throw LibEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void addProcessToWatch(string process) {
    LibEnginePINVOKE.Engine_addProcessToWatch(swigCPtr, process);
    if (LibEnginePINVOKE.SWIGPendingException.Pending) throw LibEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void removeProcessToWatch(string process) {
    LibEnginePINVOKE.Engine_removeProcessToWatch(swigCPtr, process);
    if (LibEnginePINVOKE.SWIGPendingException.Pending) throw LibEnginePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
