//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace LibEngine {

public class EngineOptions : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal EngineOptions(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(EngineOptions obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~EngineOptions() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LibEnginePINVOKE.delete_EngineOptions(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string vodPath {
    set {
      LibEnginePINVOKE.EngineOptions_vodPath_set(swigCPtr, value);
      if (LibEnginePINVOKE.SWIGPendingException.Pending) throw LibEnginePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = LibEnginePINVOKE.EngineOptions_vodPath_get(swigCPtr);
      if (LibEnginePINVOKE.SWIGPendingException.Pending) throw LibEnginePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string clipPath {
    set {
      LibEnginePINVOKE.EngineOptions_clipPath_set(swigCPtr, value);
      if (LibEnginePINVOKE.SWIGPendingException.Pending) throw LibEnginePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = LibEnginePINVOKE.EngineOptions_clipPath_get(swigCPtr);
      if (LibEnginePINVOKE.SWIGPendingException.Pending) throw LibEnginePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string screenshotPath {
    set {
      LibEnginePINVOKE.EngineOptions_screenshotPath_set(swigCPtr, value);
      if (LibEnginePINVOKE.SWIGPendingException.Pending) throw LibEnginePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = LibEnginePINVOKE.EngineOptions_screenshotPath_get(swigCPtr);
      if (LibEnginePINVOKE.SWIGPendingException.Pending) throw LibEnginePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string matchPath {
    set {
      LibEnginePINVOKE.EngineOptions_matchPath_set(swigCPtr, value);
      if (LibEnginePINVOKE.SWIGPendingException.Pending) throw LibEnginePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = LibEnginePINVOKE.EngineOptions_matchPath_get(swigCPtr);
      if (LibEnginePINVOKE.SWIGPendingException.Pending) throw LibEnginePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string logPath {
    set {
      LibEnginePINVOKE.EngineOptions_logPath_set(swigCPtr, value);
      if (LibEnginePINVOKE.SWIGPendingException.Pending) throw LibEnginePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = LibEnginePINVOKE.EngineOptions_logPath_get(swigCPtr);
      if (LibEnginePINVOKE.SWIGPendingException.Pending) throw LibEnginePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public EngineOptions() : this(LibEnginePINVOKE.new_EngineOptions(), true) {
  }

}

}
