MACRO(standard_swig_wrapper TARGET NATIVE_TARGET NAMESPACE EXPORT_DEF SWIG_FILES)
    MESSAGE(STATUS SWIG Compile...${SWIG_FILES})
    if(WIN32)
        set(SWIG_FLAGS _WIN32)
    endif()

    set_source_files_properties(${SWIG_FILES} PROPERTIES
        CPLUSPLUS ON
        USE_TARGET_INCLUDE_DIRECTORIES TRUE
        USE_SWIG_DEPENDENCIES TRUE
    )

    swig_add_library(
        ${TARGET}
        TYPE SHARED
        LANGUAGE csharp
        SOURCES ${SWIG_FILES}
        OUTPUT_DIR ${CMAKE_CURRENT_SOURCE_DIR}/generated
    )
    set_property(TARGET ${TARGET} PROPERTY SWIG_USE_TARGET_INCLUDE_DIRECTORIES TRUE)
    set_property(TARGET ${TARGET} PROPERTY SWIG_COMPILE_DEFINITIONS ${SWIG_FLAGS} CSHARP)
    set_property(TARGET ${TARGET} PROPERTY SWIG_COMPILE_OPTIONS -namespace ${NAMESPACE})
    set_property(TARGET ${TARGET} PROPERTY SWIG_GENERATED_COMPILE_DEFINITIONS ${EXPORT_DEF} CSHARP)
    target_link_libraries(${TARGET} ${NATIVE_TARGET})
ENDMACRO()